hw02-express
KsaweryThornton/goit-nodejs-homework pull request #3
Opened 2023-08-20 19:24 UTC by KsaweryThornton

2023-08-20 21:21 UTC, RadziuMM requested changes

2023-08-20 21:21 UTC, RadziuMM commented on routes/api/contacts.js
> +    const validatedBody = responseSchema.validate(req.body);
Walidację chcemy zrobić jako pierwszą i od razu wyrzucić błąd jeśli jest nie poprawna. Teraz nawet jeśli walidacja wyrzuci błąd, to nadal addContact się wykona ponieważ jest wyżej. dodatkowo przy res trzeba nadać status 201 ponieważ aktualnie zwracasz 200 ( pole w body to nie to samo co status odpowiedzi). Oraz przy 400 możemy wyrzucić błąd przekazywany przez JOI wtedy będzie wiadomo które pole jest niepoprawne.

```
try {
const validatedBody = responseSchema.validate(req.body);
   if (validatedBody.error) {
      return res.status(400).json({ message: validatedBody.error.message });
   }
   const newContact = await addContact(req.body);
   res.status(201).json({
      status: "success",
      code: 201,
      data: { newContact },
    });
} catch (error) {
  console.error(error);
  res.status(500).json({ error: "Unknow error occured." })
}
```

I najlepiej w catch nie rób next(error) tylko tak jak tu pokazałem res.status(500)

2023-08-20 21:21 UTC, RadziuMM commented on routes/api/contacts.js
> +      res.status(400).json({ message: "Missing fields" });
return res.status(400).json({ message: error.message });

2023-08-20 21:21 UTC, RadziuMM commented on routes/api/contacts.js
> +router.delete("/:contactId", async (req, res, next) => {
Tu dodajemy try catch na całość gdyby removeContact wyrzuciło błąd (tak jak masz w post i put).

2023-08-20 21:21 UTC, RadziuMM commented on models/contacts.js
Tu w tym pliku raczej nie powinno być try/catchy.

W api/contacts wywołujemy te funckcje z `await` co sprawi że jeśli w tym pliku wyrzuci błąd to zostanie przeciągnięty on do miejsca gdzie jest wywołana funkcja czyli do api/contacts.js i tam powinien być try/catch który w razie błędu wyrzuci res.status(500)

2023-08-20 21:21 UTC, RadziuMM commented on models/contacts.js
> +const validatedBody = responseSchema.validate(body);
Tu już nie potrzebna jest ponowna walidacja. Zrobiliśmy ją w api/contacts

2023-08-20 21:21 UTC, RadziuMM commented on models/contacts.js
> +      const validatedBody = responseSchema.validate(body);
Tu już nie potrzebna jest ponowna walidacja. Zrobiliśmy ją w api/contacts

2023-08-20 21:21 UTC, RadziuMM commented on routes/api/contacts.js
> +    const { error } = responseSchema.validate(req.body);
Tu raczej możemy dać osobną scheme taką bez required(). By użytkownik mógł zaktualizować np tylko pole email

2023-08-21 14:21 UTC, KsaweryThornton commented
Wprowadziłem poprawki zgodnie z instrukcjami :)

2023-08-21 19:22 UTC, RadziuMM approved these changes
Jest ok, zaliczam. Użyj proszę priettera czy czegoś do formatowania bo miejscami masz rozjechane wcięcia (spacje, odstępy) w kodzie.

2023-08-24 16:59 UTC, merged